apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  template:
    spec:
      containers:
        - name: frontend-ecommerce
          image: bytegenius/frontend-ecommerce:v0.3-staging
