apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      name: frontend-ecommerce
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-ecommerce
          ports:
            - containerPort: 80
